/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MapaRouteImport } from './routes/mapa'
import { Route as NotificacionesRouteImport } from './routes/notificaciones'
import { Route as ObrasRouteImport } from './routes/obras'
import { Route as ParaderosRouteImport } from './routes/paraderos'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as ReportesRouteImport } from './routes/reportes'
import { Route as ObrasIdRouteImport } from './routes/obras.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaRoute = MapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificacionesRoute = NotificacionesRouteImport.update({
  id: '/notificaciones',
  path: '/notificaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const ObrasRoute = ObrasRouteImport.update({
  id: '/obras',
  path: '/obras',
  getParentRoute: () => rootRouteImport,
} as any)
const ParaderosRoute = ParaderosRouteImport.update({
  id: '/paraderos',
  path: '/paraderos',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportesRoute = ReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => rootRouteImport,
} as any)
const ObrasIdRoute = ObrasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ObrasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mapa': typeof MapaRoute
  '/notificaciones': typeof NotificacionesRoute
  '/obras': typeof ObrasRouteWithChildren
  '/paraderos': typeof ParaderosRoute
  '/perfil': typeof PerfilRoute
  '/reportes': typeof ReportesRoute
  '/obras/$id': typeof ObrasIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mapa': typeof MapaRoute
  '/notificaciones': typeof NotificacionesRoute
  '/obras': typeof ObrasRouteWithChildren
  '/paraderos': typeof ParaderosRoute
  '/perfil': typeof PerfilRoute
  '/reportes': typeof ReportesRoute
  '/obras/$id': typeof ObrasIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mapa': typeof MapaRoute
  '/notificaciones': typeof NotificacionesRoute
  '/obras': typeof ObrasRouteWithChildren
  '/paraderos': typeof ParaderosRoute
  '/perfil': typeof PerfilRoute
  '/reportes': typeof ReportesRoute
  '/obras/$id': typeof ObrasIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mapa'
    | '/notificaciones'
    | '/obras'
    | '/paraderos'
    | '/perfil'
    | '/reportes'
    | '/obras/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mapa'
    | '/notificaciones'
    | '/obras'
    | '/paraderos'
    | '/perfil'
    | '/reportes'
    | '/obras/$id'
  id:
    | '__root__'
    | '/'
    | '/mapa'
    | '/notificaciones'
    | '/obras'
    | '/paraderos'
    | '/perfil'
    | '/reportes'
    | '/obras/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MapaRoute: typeof MapaRoute
  NotificacionesRoute: typeof NotificacionesRoute
  ObrasRoute: typeof ObrasRouteWithChildren
  ParaderosRoute: typeof ParaderosRoute
  PerfilRoute: typeof PerfilRoute
  ReportesRoute: typeof ReportesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa': {
      id: '/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof MapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notificaciones': {
      id: '/notificaciones'
      path: '/notificaciones'
      fullPath: '/notificaciones'
      preLoaderRoute: typeof NotificacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obras': {
      id: '/obras'
      path: '/obras'
      fullPath: '/obras'
      preLoaderRoute: typeof ObrasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paraderos': {
      id: '/paraderos'
      path: '/paraderos'
      fullPath: '/paraderos'
      preLoaderRoute: typeof ParaderosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reportes': {
      id: '/reportes'
      path: '/reportes'
      fullPath: '/reportes'
      preLoaderRoute: typeof ReportesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obras/$id': {
      id: '/obras/$id'
      path: '/$id'
      fullPath: '/obras/$id'
      preLoaderRoute: typeof ObrasIdRouteImport
      parentRoute: typeof ObrasRoute
    }
  }
}

interface ObrasRouteChildren {
  ObrasIdRoute: typeof ObrasIdRoute
}

const ObrasRouteChildren: ObrasRouteChildren = {
  ObrasIdRoute: ObrasIdRoute,
}

const ObrasRouteWithChildren = ObrasRoute._addFileChildren(ObrasRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MapaRoute: MapaRoute,
  NotificacionesRoute: NotificacionesRoute,
  ObrasRoute: ObrasRouteWithChildren,
  ParaderosRoute: ParaderosRoute,
  PerfilRoute: PerfilRoute,
  ReportesRoute: ReportesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
